version: 2

sources:
  - name: tpch_raw
    database: tpch
    schema: sf1
    loader: trino
    
    quoting:
      database: false
      schema: false
      identifier: false
      
    tables:
      - name: customer
      - name: lineitem
      - name: nation
      - name: orders
      - name: part
      - name: partsupp
      - name: region
      - name: supplier
